### ISSUE TITLE
Ошибки с фулл хуками, или что не так с вашим модом.

### ISSUE THREAD

**Issue by Zaxar163** [GloomyFolken/HookLib#4]
Любой мод на хуки должен иметь возможность full хука тела метода, каковой не предоставляется.
Какая у вашего мода лицензия? Или можно продолжить разработку мода.

**Comment by GloomyFolken** [comment]
Читайте туториал: https://goo.gl/kZyfiE
по-настоящему тело метода не заменяется, вместо этого можно вставить в начала метода конструкцию, которая будет возвращать то что вам нужно, так что разницы никакой нет: @Hook(returnCondition = ALWAYS)

Лицензия - MIT.
